(() => {
const D=JSON.parse(document.getElementById('election-data').textContent);
const fallback=document.querySelector('#map-container svg');
const bounds=fallback.viewBox.baseVal;
const G={w:bounds.width,h:bounds.height,paths:Object.fromEntries([...fallback.querySelectorAll('path[data-code]')].map(p=>[p.dataset.code,p.getAttribute('d')]))};
const units=D.units, byCode=Object.fromEntries(units.map(d=>[d.c,d]));
const parties=['Labour','Conservative','Reform UK','Lib Dem','Green','SNP','Plaid Cymru'];
const base={'Labour':26.5,'Conservative':19.75,'Reform UK':23.5,'Lib Dem':11,'Green':9.25,'SNP':2,'Plaid Cymru':1};
const colors={'Labour':'#dc4949','Conservative':'#4c84d8','Reform UK':'#48a7bd','Lib Dem':'#e9ac50','Green':'#55ad67','SNP':'#f4d469','Plaid Cymru':'#71b08a','DUP':'#ca793d','Sinn Féin':'#378c65','SDLP':'#ba6776','Alliance':'#dfbb62','UUP':'#519ac2','TUV':'#724ea4','Independent':'#888b98','Other':'#888b98'};
const state={layer:'projection',ref:23.5,sel:null};
const safe=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const share=(d,p)=>100*d.a.filter(a=>a[0]===p).reduce((s,a)=>s+a[1],0)/d.v;
function estimate(d,ref=state.ref){
 const v={}; d.a.forEach(([p,n])=>v[p]=p==='Independent'?Math.max(v[p]||0,100*n/d.v):(v[p]||0)+100*n/d.v);
 if(d.t!=='Northern Ireland') for(const p of parties) v[p]=Math.max(0,(v[p]||0)+((p==='Reform UK'?ref:p==='Labour'?base.Labour-(ref-base['Reform UK']):base[p])-D.nat[p]));
 const ranked=Object.entries(v).sort((a,b)=>b[1]-a[1]);
 return {winner:ranked[0][0],margin:ranked[0][1]-ranked[1][1],ranked};
}
const proj={}, low={}, high={};
function recalc(){for(const d of units){proj[d.c]=estimate(d);low[d.c]=estimate(d,21);high[d.c]=estimate(d,27);}}
const map=document.getElementById('map-container'),svgNS='http://www.w3.org/2000/svg';
map.replaceChildren(); const svg=document.createElementNS(svgNS,'svg');svg.setAttribute('viewBox',`0 0 ${G.w} ${G.h}`);svg.setAttribute('role','img');svg.setAttribute('aria-label','Map of 650 Westminster constituencies by selected election layer');svg.id='map';map.append(svg);
const shapes={};
for(const d of units){const p=document.createElementNS(svgNS,'path');p.setAttribute('d',G.paths[d.c]);p.setAttribute('class','seat');p.setAttribute('tabindex','0');p.setAttribute('role','button');p.setAttribute('aria-label',`${d.n}, ${d.r}`);p.dataset.code=d.c;p.addEventListener('click',()=>select(d.c));p.addEventListener('keydown',e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();select(d.c);}});svg.append(p);shapes[d.c]=p;}
const legend=document.getElementById('legend');
function color(d){if(state.layer==='result')return colors[d.w]||colors.Other;if(state.layer==='projection')return colors[proj[d.c].winner]||colors.Other;if(state.layer==='battleground')return low[d.c].winner!==high[d.c].winner?colors[proj[d.c].winner]||colors.Other:'#40464e';if(state.layer==='share'){let n=share(d,'Reform UK');return n<10?'#e3e7f0':n<20?'#b6d8e2':n<30?'#76b9cb':n<40?'#388aa2':'#14516d';}let n=d.h;if(n==null)return '#707680';return n<-15?'#173f72':n<-5?'#5279ae':n<5?'#c6cad1':n<15?'#eda0a0':'#ba424a';}
function renderMap(){for(const d of units){const p=shapes[d.c];p.setAttribute('fill',color(d));p.classList.toggle('sel',d.c===state.sel);p.setAttribute('aria-label',`${d.n}: ${state.layer==='result'?d.w:state.layer==='projection'?proj[d.c].winner:state.layer==='battleground'?(low[d.c].winner!==high[d.c].winner?'changes winner in range':'stable in range'):state.layer==='share'?share(d,'Reform UK').toFixed(1)+'% Reform UK':d.h==null?'no comparable change':d.h+' points Labour'}`);}
 const item=(c,t)=>`<span><i class="sw" style="background:${c}"></i>${t}</span>`;
 if(state.layer==='share') legend.innerHTML=[['#e3e7f0','Under 10%'],['#b6d8e2','10–20'],['#76b9cb','20–30'],['#388aa2','30–40'],['#14516d','40+']].map(v=>item(...v)).join('');
 else if(state.layer==='change')legend.innerHTML=[['#173f72','−15 pts or more'],['#5279ae','−15 to −5'],['#c6cad1','−5 to +5'],['#eda0a0','+5 to +15'],['#ba424a','+15 or more'],['#707680','Unavailable']].map(v=>item(...v)).join('');
 else legend.innerHTML=Object.entries(colors).filter(([p])=>['Labour','Conservative','Reform UK','Lib Dem','Green','SNP','Plaid Cymru','DUP','Sinn Féin','Independent'].includes(p)).map(([p,c])=>item(c,p)).join('')+(state.layer==='battleground'?item('#40464e','Stable across Reform 21–27'):'');
 const description={projection:'Modelled winner at the selected national share. Colour does not measure certainty.',battleground:'Coloured seats change winner between Reform 21% and 27% (equal opposite Labour swing); dark seats do not.',result:'Actual 2024 first-past-the-post winner. This is not a map of current MP affiliations.',share:'Reform UK local first-choice share in July 2024; zero where it did not field a candidate.',change:'Labour candidate vote-share change from notional 2019 to 2024 on 2024 boundaries; grey means missing.'};document.getElementById('layer-desc').textContent=description[state.layer];}
function panel(){const el=document.getElementById('panel');if(!state.sel)return;const d=byCode[state.sel],m=proj[d.c];const old=d.a.map(([p,n])=>[p,100*n/d.v,n]).sort((a,b)=>b[1]-a[1]);el.innerHTML=`<h3>${safe(d.n)}</h3><p class="small">${safe(d.r)} · ${safe(d.t)} · <a href="https://electionresults.parliament.uk/general-elections/6/constituency-areas">Commons Library 2024 results</a></p><div class="kv"><span>2024 winner</span><strong>${safe(d.w)}</strong><span>${safe(d.person)} · majority ${d.m.toFixed(1)} points</span></div><div class="kv"><span>Uniform-swing scenario</span><strong>${safe(m.winner)}</strong><span>Margin ${m.margin.toFixed(1)} points over runner-up${d.t==='Northern Ireland'?' · unchanged 2024 votes':''}</span></div><p class="small">${d.v.toLocaleString()} valid votes · ${d.e.toLocaleString()} electors · Labour change ${d.h==null?'not available':(d.h>0?'+':'')+d.h.toFixed(1)+' pts (2019–24)'}</p><h4>2024 candidate votes</h4>${old.map(([p,s,n])=>`<div class="pb"><span>${safe(p)}</span><div class="pt"><span style="width:${Math.min(100,s*2)}%;background:${colors[p]||'#888b98'}"></span></div><span class="num">${s.toFixed(1)}% <small>(${n.toLocaleString()})</small></span></div>`).join('')}<h4>Scenario shares</h4>${m.ranked.slice(0,7).map(([p,n])=>`<div class="pb"><span>${safe(p)}</span><div class="pt"><span style="width:${Math.min(100,n*2)}%;background:${colors[p]||'#888b98'}"></span></div><span class="num">${n.toFixed(1)}%</span></div>`).join('')}<p class="small muted">Adjusted shares are not re-normalised. Ranking determines the model winner.</p>`;}
function select(c){state.sel=c;document.getElementById('search').value=byCode[c].n;renderMap();panel();}
const order=['Scotland','Wales','Northern Ireland','North East','North West','Yorkshire and The Humber','East Midlands','West Midlands','East of England','London','South East','South West'];
function tally(){const count={};units.forEach(d=>count[proj[d.c].winner]=(count[proj[d.c].winner]||0)+1);document.getElementById('tally').innerHTML=`<strong>Model seat tally · ${state.ref.toFixed(1)}% Reform, ${(base.Labour-(state.ref-base['Reform UK'])).toFixed(1)}% Labour</strong><div class="tally-items">${Object.entries(count).sort((a,b)=>b[1]-a[1]).map(([p,n])=>`<span><i class="sw" style="background:${colors[p]||colors.Other}"></i>${safe(p)} <strong>${n}</strong></span>`).join('')}</div><span class="small muted">650 total · 326 majority · Northern Ireland held at 2024 · not an MRP</span>`;
 const regions=order.map(r=>[r,units.filter(d=>d.r===r)]).filter(x=>x[1].length);let england=units.filter(d=>d.t==='England');regions.splice(3,0,['England total',england]);regions.push(['UK total',units]);
 document.getElementById('regions-body').innerHTML=regions.map(([r,ds])=>{const a={},b={};ds.forEach(d=>{a[d.w]=(a[d.w]||0)+1;b[proj[d.c].winner]=(b[proj[d.c].winner]||0)+1;});const top=x=>Object.entries(x).sort((a,b)=>b[1]-a[1])[0];const close=ds.filter(d=>proj[d.c].margin<5).length;return `<tr><td>${safe(r)}</td><td class="num">${ds.length}</td><td>${safe(top(a)[0])} ${top(a)[1]}</td><td>${safe(top(b)[0])} ${top(b)[1]}</td><td class="num">${b.Labour||0}</td><td class="num">${b['Reform UK']||0}</td><td class="num">${b.Conservative||0}</td><td class="num">${close}</td></tr>`;}).join('');}
function render(){recalc();renderMap();tally();panel();document.getElementById('scenario-label').textContent=state.ref.toFixed(1)+'%';document.getElementById('shares-label').textContent=`Labour ${(base.Labour-(state.ref-base['Reform UK'])).toFixed(1)}% · Conservative ${base.Conservative.toFixed(1)}% · Lib Dem 11% · Green 9.25%`;}
document.getElementById('layers').addEventListener('click',e=>{let b=e.target.closest('button[data-layer]');if(!b)return;state.layer=b.dataset.layer;document.querySelectorAll('#layers button').forEach(x=>x.setAttribute('aria-pressed',String(x===b)));renderMap();});
document.getElementById('swing').addEventListener('input',e=>{state.ref=Number(e.target.value);render();});document.querySelectorAll('[data-preset]').forEach(b=>b.addEventListener('click',()=>{state.ref=Number(b.dataset.preset);document.getElementById('swing').value=state.ref;render();}));
const search=document.getElementById('search'), nameToCode=new Map(units.map(d=>[d.n.toLowerCase(),d.c]));document.getElementById('seats').innerHTML=units.map(d=>`<option value="${safe(d.n)}"></option>`).join('');search.addEventListener('change',()=>{const c=nameToCode.get(search.value.toLowerCase());if(c)select(c);});search.addEventListener('input',()=>{const c=nameToCode.get(search.value.toLowerCase());if(c)select(c);});
const names=['Houghton and Sunderland South','Doncaster North','Basildon and Billericay','Pontefract, Castleford and Knottingley'];document.getElementById('examples').textContent=names.map(n=>{const d=units.find(x=>x.n===n);return d?`${n}: ${d.w} by ${d.m.toFixed(1)} pts over ${d.a[1][0]} (${d.a[0][1].toLocaleString()} to ${d.a[1][1].toLocaleString()} votes)`:''}).filter(Boolean).join('; ')+'.';
render();
})();
